from app.models.user import User
from app.models.district import District
from app.models.socioeconomic_indicator import SocioeconomicIndicator
from app.models.waste_generation import WasteGeneration
from app.models.recycling_point import RecyclingPoint
from app.models.candidate_zone import CandidateZone
from app.models.dataset import Dataset
from app.models.audit_log import AuditLog
from app.models.model_version import ModelVersion
